#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""gen_from_firmware_config.py — derive the MoveIt config from litearm-stm32 firmware parameter tables.

Why derive instead of copying by hand
-------------------------------------
The limits/velocities/accelerations in ``config/joint_limits.yaml`` all come
from the **firmware parameter tables** (``User/litearm/params/defaults.c`` and
the ``joint_limit_macros.h`` it includes):

* Position limits ← ``JL_QMIN_Jn / JL_QMAX_Jn`` (generated by
  ``tools/export_model.py`` by shrinking the URDF hard limits by 1°). Note that
  these are **deliberately 1° narrower** than the ``<limit>`` in the URDF (the
  URDF says -2.827, this says -2.809547); that is the project's own safety
  margin. MoveIt's planning space should match the **firmware's runtime safety
  envelope**, otherwise it plans out of bounds and the firmware rejects it,
  which shows up as "planning succeeds but execution fails".
* Velocity/acceleration/jerk ← ``joint[].vel_max / acc_max / jerk``

The jerk limit is not just "one more constraint": without a jerk limit,
``AddRuckigTrajectorySmoothing`` (double S-curve, jerk-limited velocity
planning) falls back to a built-in default rather than the envelope the project
tuned — so MoveIt and the firmware's move_j S-curve would not constrain jerk
the same way at all. It has to be carried over along with the rest.

Copying these 7×4 numbers by hand is extremely error-prone, and changing the
firmware parameters afterwards gives no warning whatsoever. So we make it a
generator that can be re-run: **re-run it whenever the firmware parameter tables
change**.

Why the expected source is the firmware and not pylitearm
---------------------------------------------------------
After the underlying layer was swapped, the authoritative source for joint
limits and motion envelopes is the firmware parameter tables (the daemon reads
these values back with 0x24 at startup, see the "firmware identity" log in
hw_daemon.py). The ROS side should not have a second set of answers of its own —
that is exactly where "you change something, nothing happens, and it is very
hard to trace" comes from.

Usage::

    python3 gen_from_firmware_config.py                    # finds litearm-stm32 automatically
    python3 gen_from_firmware_config.py --firmware-root <path>
    python3 gen_from_firmware_config.py --check            # only check sync, write nothing

When the firmware repository is not found: ``--check`` returns 2 (cannot verify,
kept distinct from "out of sync"), and without ``--check`` it exits with an
error — it **does not write a set of guessed values**.
"""

import argparse
import os
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Sequence

NUM_JOINTS = 7

HEADER = """# joint_limits.yaml — joint limits for MoveIt planning.
#
# Every value comes from the litearm-stm32 firmware parameter tables
# (User/litearm/params/defaults.c and joint_limit_macros.h), not from the raw
# values in the URDF: the firmware limits are deliberately 1° narrower than the
# URDF, which is the project's own safety margin. Keeping MoveIt's planning
# space consistent with the firmware's runtime safety envelope avoids plans
# that go out of bounds and get rejected by the firmware.
#
# The jerk limits are used by AddRuckigTrajectorySmoothing (double S-curve);
# without them Ruckig falls back to its own defaults, which do not match the
# firmware's move_j S-curve envelope.
#
# ⚠️ This file is generated by tools/gen_from_firmware_config.py, do not edit it
#    by hand. After changing the firmware parameter tables, re-run:
#      python3 tools/gen_from_firmware_config.py --firmware-root <litearm-stm32>
"""

INITIAL_HEADER = """# initial_positions.yaml — initial joint angles for startup/RViz interaction.
#
# All zeros (matching the firmware's zero point).
# Generated by tools/gen_from_firmware_config.py.
"""


def find_firmware_root(explicit: Optional[str] = None) -> Optional[str]:
    """Locate the litearm-stm32 repository; return ``None`` if not found.

    It is **a separate repository**, not inside this workspace, so we look in the
    conventional locations and also allow an explicit override.
    """
    candidates = [explicit, os.environ.get("LITEARM_STM32_ROOT"),
                  os.path.join(os.path.expanduser("~"), "wkspace",
                               "litearm-stm32")]
    # <ws>/src/<pkg>/tools → walk up to <ws>, then look for a sibling litearm-stm32
    here = Path(__file__).resolve()
    workspace = here.parents[3]          # src/<pkg>/tools/xxx.py → <ws>
    candidates.append(str(workspace.parent / "litearm-stm32"))
    for path in candidates:
        if path and os.path.isdir(path):
            return path
    return None


def _macros(path: Path) -> Dict[str, float]:
    """Read limit macros of the form ``#define JL_XXX_Jn (v f)``."""
    out: Dict[str, float] = {}
    text = path.read_text(encoding="utf-8")
    for name, value in re.findall(
            r"#define\s+(JL_\w+)\s+\(\s*(-?[\d.]+)f\s*\)", text):
        out[name] = float(value)
    return out


def _joint_table(text: str) -> Dict[int, Dict[str, object]]:
    """Extract the 7-joint parameter table from the text of ``defaults.c``.

    Split into blocks on ``.can_id=0x``, then identify the joint number via
    ``q_min=JL_QMIN_Jn`` — do **not** identify it by can_id: the single-joint
    bench table (``#if LITEARM_BENCH_1J``) also uses can_id 0x01, which would mix
    the bench parameters in; but the bench table's q_min is a literal (-12.0f),
    so using that as the criterion rules it out naturally.
    """
    joints: Dict[int, Dict[str, object]] = {}
    for block in text.split(".can_id=0x")[1:]:
        match = re.search(r"q_min=(JL_QMIN_J\d)", block)
        if not match:
            continue
        q_min_macro = match.group(1)
        q_max_match = re.search(r"q_max=(JL_QMAX_J\d)", block)
        if not q_max_match:
            raise ValueError(f"joint block has {q_min_macro} but no matching q_max macro")
        joints[int(q_min_macro[-1]) - 1] = {
            "q_min_macro": q_min_macro,
            "q_max_macro": q_max_match.group(1),
            "vel_max": _field(block, "vel_max"),
            "acc_max": _field(block, "acc_max"),
            "jerk": _field(block, "jerk"),
        }
    return joints


def _field(block: str, name: str) -> float:
    """Get the numeric value of a ``.name=1.0f`` field.

    The leading ``\\.`` stops ``.tau_max`` from matching ``.wall_tau_max``.
    """
    match = re.search(rf"\.{name}=(-?[\d.]+(?:[eE][-+]?\d+)?)f", block)
    if not match:
        raise ValueError(f"no .{name}= found in the joint block "
                         f"(did the source layout change?)")
    return float(match.group(1))


def load_joints(root: str) -> List[Dict[str, float]]:
    """Read the limits and motion envelope of the 7 joints; ValueError on any mismatch."""
    root_path = Path(root)
    macros = _macros(root_path / "User" / "litearm" / "params"
                     / "joint_limit_macros.h")
    text = (root_path / "User" / "litearm" / "params" / "defaults.c"
            ).read_text(encoding="utf-8")
    table = _joint_table(text)
    if sorted(table) != list(range(NUM_JOINTS)):
        raise ValueError(
            f"parsed joints {sorted(table)} from defaults.c, expected "
            f"0..{NUM_JOINTS - 1} (the parser has to keep up with the source "
            f"layout)")

    out: List[Dict[str, float]] = []
    for index in range(NUM_JOINTS):
        entry = table[index]
        for macro_key in ("q_min_macro", "q_max_macro"):
            name = entry[macro_key]
            if name not in macros:
                raise ValueError(f"{name} not found in joint_limit_macros.h")
        out.append({
            "q_min": macros[entry["q_min_macro"]],
            "q_max": macros[entry["q_max_macro"]],
            "vel_max": entry["vel_max"],
            "acc_max": entry["acc_max"],
            "jerk": entry["jerk"],
        })
    return out


def render_joint_limits(joints: List[Dict[str, float]]) -> str:
    lines: List[str] = [HEADER]
    lines.append("joint_limits:")
    for index, joint in enumerate(joints):
        lines += [
            f"  joint{index + 1}:",
            "    has_position_limits: true",
            f"    min_position: {joint['q_min']:.6f}",
            f"    max_position: {joint['q_max']:.6f}",
            "    has_velocity_limits: true",
            f"    max_velocity: {joint['vel_max']:.6f}",
            "    has_acceleration_limits: true",
            f"    max_acceleration: {joint['acc_max']:.6f}",
            "    has_jerk_limits: true",
            f"    max_jerk: {joint['jerk']:.6f}",
            "",
        ]
    return "\n".join(lines)


def render_initial_positions() -> str:
    return INITIAL_HEADER + "initial_positions:\n" + "".join(
        f"  joint{i}: 0.0\n" for i in range(1, NUM_JOINTS + 1))


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--firmware-root", default=None,
                        help="litearm-stm32 repository root (found "
                             "automatically by default; the LITEARM_STM32_ROOT "
                             "environment variable also works)")
    parser.add_argument("--output-dir",
                        default=str(Path(__file__).resolve().parents[1] / "config"),
                        help="output directory (defaults to this package's config/)")
    parser.add_argument("--check", action="store_true",
                        help="only check whether the existing files match the "
                             "derived result, write nothing")
    args = parser.parse_args(list(argv) if argv is not None else None)

    root = find_firmware_root(args.firmware_root)
    if root is None:
        if args.check:
            print("⚠ litearm-stm32 repository not found, cannot verify "
                  "(returns 2, kept distinct from being out of sync)")
            return 2
        print("✗ litearm-stm32 repository not found. Pass --firmware-root, or set "
              "LITEARM_STM32_ROOT.\n"
              "  **It will not write a set of guessed values** — limits and "
              "motion envelopes are safety parameters.",
              file=sys.stderr)
        return 2

    try:
        joints = load_joints(root)
    except ValueError as exc:
        print(f"✗ failed to parse the firmware parameter tables: {exc}",
              file=sys.stderr)
        return 2
    print(f"Firmware parameter tables: {root}")

    output_dir = Path(args.output_dir)
    targets = {
        output_dir / "joint_limits.yaml": render_joint_limits(joints),
        output_dir / "initial_positions.yaml": render_initial_positions(),
    }

    stale: List[str] = []
    for path, content in targets.items():
        if args.check:
            existing = path.read_text(encoding="utf-8") if path.exists() else ""
            if existing != content:
                stale.append(str(path))
            continue
        path.write_text(content, encoding="utf-8")
        print(f"✓ wrote {path}")

    if args.check:
        if stale:
            print("✗ the following files are out of sync with the firmware "
                  "parameter tables:")
            for path in stale:
                print(f"    {path}")
            print("  Run: python3 tools/gen_from_firmware_config.py")
            return 1
        print("✓ joint_limits.yaml / initial_positions.yaml match the firmware "
              "parameter tables")
    return 0


if __name__ == "__main__":
    sys.exit(main())
